# Generated by Django 4.2.14 on 2024-07-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_persona_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
