# Generated by Django 4.2.14 on 2024-07-20 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_citamedica_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedientemedico',
            old_name='alergias',
            new_name='enfermedad',
        ),
    ]
