# Generated by Django 4.2.14 on 2024-07-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_rename_alergias_expedientemedico_enfermedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
