# Generated by Django 4.2.14 on 2024-07-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0009_doctor_numero_licencia_enfermera_licencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='numero_licencia',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enfermera',
            name='licencia',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
