# Generated by Django 4.2.14 on 2024-07-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_expedientemedico_delete_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
