# Generated by Django 4.2.14 on 2024-07-28 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_alter_persona_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenMedico',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo_de_examen', models.CharField(max_length=100)),
                ('resultado', models.TextField()),
                ('costo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('historial_medico', models.TextField()),
                ('notas_medicas', models.TextField(blank=True, null=True)),
                ('examenes_medicos', models.ManyToManyField(related_name='expedientes', to='Hospital.examenmedico')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible_para_citas', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('dosis', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='expedientemedico',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='enfermera',
            name='numero_licencia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='enfermedades',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='numero_historia_clinica',
        ),
        migrations.AddField(
            model_name='administrador',
            name='tipo_de_personal',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Enfermera', 'Enfermera')], default='Doctor', max_length=50),
        ),
        migrations.AddField(
            model_name='enfermera',
            name='area_de_asignacion',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='enfermera',
            name='licencia',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='id_empleado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='persona_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Hospital.persona'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='numero_licencia',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='CitaMedica',
        ),
        migrations.DeleteModel(
            name='ExpedienteMedico',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='Hospital.paciente'),
        ),
        migrations.AddField(
            model_name='examenmedico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_medicos', to='Hospital.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='Hospital.doctor'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='Hospital.paciente'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='horario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doctores', to='Hospital.horarioatencion'),
        ),
        migrations.AddField(
            model_name='enfermera',
            name='turno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='enfermeras', to='Hospital.horarioatencion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='expedientes',
            field=models.ManyToManyField(related_name='pacientes', to='Hospital.expediente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='historial_medicamentos',
            field=models.ManyToManyField(related_name='pacientes', to='Hospital.medicamento'),
        ),
    ]
