# Generated by Django 4.2.14 on 2024-07-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_cita_examenmedico_expediente_horarioatencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='numero_licencia',
        ),
        migrations.RemoveField(
            model_name='enfermera',
            name='licencia',
        ),
    ]
