# Generated by Django 4.2.14 on 2024-07-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0008_remove_doctor_numero_licencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='numero_licencia',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='enfermera',
            name='licencia',
            field=models.CharField(default='', max_length=50),
        ),
    ]
