# Generated by Django 4.2.14 on 2024-07-31 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_alter_doctor_numero_licencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenmedico',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='horario',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctores', to='Hospital.horarioatencion'),
        ),
        migrations.AlterField(
            model_name='enfermera',
            name='turno',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfermeras', to='Hospital.horarioatencion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contacto de Emergencia'),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='expedientes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='historial_medicamentos',
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='expedientes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='Hospital.expediente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='historial_medicamentos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='Hospital.medicamento'),
        ),
    ]
