# Generated by Django 4.2.14 on 2024-08-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0011_remove_examenmedico_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='tipo_de_personal',
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('General', 'General'), ('Cardiologo', 'Cardiologo'), ('Dermatologo', 'Dermatologo'), ('Ginecologo', 'Ginecologo'), ('Pediatra', 'Pediatra'), ('Psicologo', 'Psicologo'), ('Psiquiatra', 'Psiquiatra'), ('Urologo', 'Urologo'), ('Odontologo', 'Odontologo'), ('Neurologo', 'Neurologo')], default='General', max_length=100),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='horario',
        ),
        migrations.AlterField(
            model_name='enfermera',
            name='area_de_asignacion',
            field=models.CharField(choices=[('Emergencias', 'Emergencias'), ('Cuidados Intensivos', 'Cuidados Intensivos'), ('Quirófano', 'Quirófano'), ('Pediatría', 'Pediatría'), ('Maternidad', 'Maternidad'), ('Cardiología', 'Cardiología'), ('Medicina Interna', 'Medicina Interna')], default='Emergencias', max_length=100),
        ),
        migrations.RemoveField(
            model_name='enfermera',
            name='turno',
        ),
        migrations.AlterField(
            model_name='examenmedico',
            name='tipo_de_examen',
            field=models.CharField(choices=[('Análisis de Sangre', 'Análisis de Sangre'), ('Análisis de Orina', 'Análisis de Orina'), ('Hemograma', 'Hemograma'), ('Electrocardiograma', 'Electrocardiograma'), ('Ecografía (Ultrasonido)', 'Ecografía (Ultrasonido)'), ('Rayos X', 'Rayos X'), ('Prueba de Embarazo', 'Prueba de Embarazo')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='dia_semana',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default='', max_length=15),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='historial_medicamentos',
        ),
        migrations.AddField(
            model_name='doctor',
            name='horario',
            field=models.ManyToManyField(related_name='doctores', to='Hospital.horarioatencion'),
        ),
        migrations.AddField(
            model_name='enfermera',
            name='turno',
            field=models.ManyToManyField(related_name='enfermeras', to='Hospital.horarioatencion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='historial_medicamentos',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='Hospital.medicamento'),
        ),
    ]
