# Generated by Django 4.2.14 on 2024-08-01 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0012_remove_administrador_tipo_de_personal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='examenes_medicos',
        ),
        migrations.AddField(
            model_name='expediente',
            name='examenes_medicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='Hospital.examenmedico'),
        ),
    ]
