# Generated by Django 4.2.14 on 2024-08-01 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0013_remove_expediente_examenes_medicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenmedico',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes_medicos', to='Hospital.paciente'),
        ),
    ]
