# Generated by Django 4.2.14 on 2024-08-01 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0014_examenmedico_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='horario',
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='dia_semana',
            field=models.CharField(choices=[('Lunes - Viernes', 'Lunes - Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='doctor',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctores', to='Hospital.horarioatencion'),
        ),
    ]
