# Generated by Django 4.2.14 on 2024-08-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0015_remove_doctor_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='numero_licencia',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
